### ISSUE TITLE
Clickable monster + question 

### ISSUE THREAD

**Issue by pygmychameleon** [shashahchk/omegacity-phaser#20]
- Make monster clickable to enable question pop-up 
- Button to close pop-up
- Button to submit answer for question
**- Validate answer AND Update points for each team (most probably server-side)**
- Destroy monster upon completion (destroy())

**Comment by winson8222** [comment]
Yet to destroy monster because there is only one monster, wait til more monster spawn

**Comment by shashahchk** [comment]
fixed by #65
